---

name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.11-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (mix)
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Install (deps)
        run: mix deps.get

      - name: Run Tests
        run: mix test

  Format:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.11-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (mix)
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted
